### ISSUE TITLE
small link issue

### ISSUE THREAD

**Issue by JustinGOSSES** [houstondatavis/data-jams#14]
When I go to the data-jams page and click on a data jam link with a single left mouse click it changes the default data jam data shown to be that data jam. However, if I try to open that link in a new page, using a right click, I get a 404 error as the url opened as https://houstondatavis.github.io/data-jams/december-2016 and not https://houstondatavis.github.io/data-jams/#!/december-2016. Note, the #! is missing in the first.

**Comment by pandafulmanda** [comment]
good catch, thanks!
